### PR TITLE
Refactor Makefile

### PR DESCRIPTION
**Pull request by steveschnepp**
* Adding -pipe to compile faster
* Optional LTO
* Using wildcard for sources files
* Removing CPP compilation rules, since it is unused
* Remove warnings

### CODE REVIEW

**Comment by jarikomppa** [comment]
PR has content from other PRs?

**Comment by steveschnepp** [comment]
Yes. It fixes the same thing as #10 

Let me fix this one to ensure it merges smoothly.

**Comment by steveschnepp** [comment]
I removed the already-fixed `extern`.
Should apply cleanly now.

**Comment by steveschnepp** [comment]
> PR has content from other PRs?
And yes, usually I try to open multiple piecemeal PR. But as sometimes one or two is depending on a central one, accepting a leaf will also merge the central one.

**Pull request merged**
