### PR TITLE
Serial Enhancement 

### PR DESCRIPTION
**Pull request by steveschnepp**
I'm going to try to implement the whole serial behavior.
But right now I'm a little struggling with your handling of interrupts. As the various code tries to reverse engineer what happens in other runs.

I already had the issue thay i had to create new state (number of bits sent).

I think that we might need to simply emulate the internal hidden d-latches that are in the MCU instead of trying to infer what happened by looking at the current SFR state.

### CODE REVIEW

**Comment by jarikomppa** [comment]
As far as I recall the interrupts were not implemented completely, so they're probably a mess.

**Comment by steveschnepp** [comment]
> so they're probably a mess

So, I guess you won't mind me refactoring that part a bit ?

**Comment by jarikomppa** [comment]
Feel free to rewrite the whole thing if you feel like it =)

**Comment by steveschnepp** [comment]
I'll try without, let's see.

**Comment by steveschnepp** [comment]
Well, i won't work much more on that one for the time being, as it fulfills it purpose. 

And RX is painful for now in the UI, we don't have a good way to interact automatically with the emulator.

**Pull request merged**
